spring:
  flyway:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:fsa41306@127.0.0.1:3306/Marketplace?useTimezone=true&serverTimezone=UTC
    user: root
    password: fsa41306
    schemas: Marketplace
#    baseline-on-migrate: true
